name: restaurant_foodly
description: "Foodly Restaurant App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.3
  http: ^1.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  firebase_core: ^2.30.1
  firebase_database: ^10.3.8
  firebase_auth: ^4.17.8
  otp_text_field: ^1.1.3
  cloud_firestore: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/